overwrite: true
schema: "http://localhost:8080/graphql"
documents:
  - "src/**/*.graphql"
extensions:
  endpoints:
    default:
      url: "http://localhost:8080/graphql"
generates:
  ./src/utils/graphql/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typed-document-node"
    config:
      avoidOptionals:
        objet: true
        field: true
